fix type declaration exports
Fixes error when bundling project that uses `dasha`:

Error: Build failed with 1 error:

[MISSING_EXPORT] Error: "Element" is not exported by "../../dasha/node_modules/.pnpm/@xmldom+xmldom@0.9.10/node_modules/@xmldom/xmldom/index.d.ts".
   ╭─[ ../../dasha/dist/index.d.mts:3:10 ]
   │
 3 │ import { Element } from "@xmldom/xmldom";
   │          ───┬───
   │             ╰───── Missing export
   │
   │ Note: If you meant to import a type rather than a value, make sure to add the `type` modifier (e.g. `import { type Foo } from '@xmldom/xmldom'`).